---
replicaCount: 1

postgresql:
  postgresqlUsername: postgres
  postgresqlPassword: password123 # Change this!
  postgresqlDatabase: mydb
  persistence:
    enabled: true
    size: 10Gi # Adjust size as needed
    storageClass: "manual" # Or your preferred StorageClass
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
