pipeline {
    agent {
        kubernetes {
            label 'dynamic-worker'
            yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: dynamic-worker
spec:
  containers:
  - name: worker
    image: postgres:14
    command: ['sh', '-c', 'export PGPASSWORD="password123"; psql -h "postgresql-postgresql" -U "postgres" -d "mydb" -c "CREATE TABLE IF NOT EXISTS time_logs (timestamp TIMESTAMP WITH TIME ZONE); INSERT INTO time_logs (timestamp) VALUES (NOW()); SELECT * FROM time_logs;"']
    env:
    - name: POSTGRES_HOST
      value: "postgresql-postgresql" # Replace with your Postgres service name
    - name: POSTGRES_USER
      value: "postgres" # Replace with your Postgres user
    - name: POSTGRES_PASSWORD
      value: "password123"
    - name: POSTGRES_DB
      value: "mydb" #Replace with your Database name.
            """
        }
    }
    triggers {
        cron('H/5 * * * *')
    }
    stages {
        stage('Run Worker') {
            steps {
                script {
                    echo 'Worker pod started'
                    sleep 10
                    echo 'Worker pod finished'
                }
            }
        }
    }
}
