apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv # Unique name for the PV
  labels:
    type: local # Or your desired label
spec:
  capacity:
    storage: 10Gi # Must match the size requested in the PVC
  volumeMode: Filesystem # Or Block if needed
  accessModes:
    - ReadWriteOnce # Must match the access modes in the PVC
  persistentVolumeReclaimPolicy: Retain # Or Delete
  storageClassName: manual # Must match the storageClassName in the PVC (or be omitted if no storageClassName is used in the PVC)
  local:
    path: /tmp/data/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-k3s-default-server-0
