apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    app: postgresql
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgresql
    release: {{ .Release.Name }}
